### ISSUE TITLE
Categorisation of RWAs

### ISSUE THREAD

**Issue by PrathmeshRanjan** [PatrickAlphaC/rwa-creator#5]
In yield farming, users stake cryptocurrencies to earn rewards, often in the form of new tokens. These reward tokens are on-chain assets indirectly backed by the staked cryptocurrencies (also on-chain). So we can put the yielded tokens in the category of On-Chain Asset with On-Chain Collateral and Indirect Backing but the paradox here is that those yielded tokens aren't a real-world asset. So can we consider them as RWAs? Seems very confusing to me. What are your views on this Patrick? I would love to know.

**Comment by PatrickAlphaC** [comment]
Great question. Yes - non-RWA tokens can have the same properties as RWA tokens. What makes a token a "Real world asset" is a bit subjective - it just comes down to what you define as "real". If you're building an RWA with an On-Chain asset, that itself might disqualify the token from being real world. 

For example, WETH is representing an On-Chain Asset (ETH), with On-Chain collateral (ETH), and is directly backed, but one would argue that ETH is not "Real world". 

DAI on the other hand, is a "Real world asset" because the asset it's representing is outside of the real world.

**Comment by PatrickAlphaC** [comment]
Let me know if that doesn't make sense.

**Comment by PrathmeshRanjan** [comment]
It makes sense if the outlook is subjective since RWAs are still very new & a naive field and don't have very concrete definitions.
